# Generated by Django 4.2.4 on 2023-08-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_pagina_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=256)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=9)),
                ("quantidade_estoque", models.IntegerField()),
            ],
        ),
    ]
